---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-ddh-data
spec:
  template:
    spec:
      initContainers:
      - name: change-permissions
        image: busybox:1.28
        command: ['chmod', '-R', '0775', '/depmap-data']
        volumeMounts:
        - name: depmap-data
          mountPath: /depmap-data
      containers:
      - name: download-ddh-data
        image: dukegcb/lando-util:0.5.4
        workingDir: /depmap-data
        command:
        - "python"
        - "-m"
        - "lando_util.stagedata"
        - "/etc/file-list.json"
        - "/depmap-data/download.log"
        volumeMounts:
        - name: depmap-data
          mountPath: "/depmap-data"
        - name: ddsclient-config
          mountPath: "/etc/ddsclient"
          readOnly: true
        - name: file-list
          mountPath: "/etc/file-list.json"
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: depmap-data
        persistentVolumeClaim:
          claimName: depmap-data-pvc
      - name: ddsclient-config
        secret:
          secretName: ddsclient-config-secret
      - name: file-list
        configMap:
          name: ddh-data-file-list

