name: Publish Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Format the target docker image repo name (must be lowercase)
      run: |
        echo "::set-env name=DOCKER_REPOSITORY::docker.pkg.github.com/$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')/ddh:latest"
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . -t ddh:${GITHUB_SHA}
    - name: Tag as latest
      run: docker tag ddh:${GITHUB_SHA} ${DOCKER_REPOSITORY}
    - name: Push Docker image
      run: docker push ${DOCKER_REPOSITORY}
